import { zipSync, strToU8 } from 'fflate';

export const buildZip = async (entries, extras = []) => {
  const files = {};

  for (const entry of entries) {
    const buffer = await entry.blob.arrayBuffer();
    files[entry.name] = new Uint8Array(buffer);
  }

  for (const extra of extras) {
    files[extra.name] = extra.data;
  }

  files['README.txt'] = strToU8(
    'Generated by Sooocojp Color Management\n' +
      'Includes color-matched images.\n'
  );

  const zipped = zipSync(files, { level: 6 });
  return new Blob([zipped], { type: 'application/zip' });
};
